### ISSUE TITLE
Does not start on slack without setting BOT_ALT_PREFIXES

### ISSUE THREAD

**Issue by kim0** [rroemhild/docker-err#11]
I started this docker container, without setting `BOT_ALT_PREFIXES`. The config.py defaulted to the name 'Err', while my bot name on slack was `mybot`, and this caused the connection to slack to fail.

**Comment by vutny** [comment]
I have recently tested the image and config file connecting to Slack backend, and this seems no longer an issue. Errbot is working fine without explicitly setting `BOT_ALT_PREFIXES`.
FYI @rroemhild

**Comment by rroemhild** [comment]
Thank you for testing!
