### ISSUE TITLE
Permission denied.

### ISSUE THREAD

**Issue by rchannel** [rroemhild/docker-err#4]
Ran:
mkdir /tmp/errbot /tmp/errbot/ssl /tmp/errbot/data /tmp/errbot/plugins /tmp/errbot/errbackends
chmod -R 755 /tmp/errbot

Then attempted to run:
docker run --name err -v /tmp/errbot:/srv -e BACKEND=Slack -e BOT_USERNAME=err -e BOT_ADMINS=@channel -e BOT_TOKEN=fgsdfgafg352XFlXRz -e "TZ=USA/Mountian" rroemhild/errbot

Error I am getting everytime.
mkdir: cannot create directory ‘/srv/data’: Permission denied
mkdir: cannot create directory ‘/srv/plugins’: Permission denied
mkdir: cannot create directory ‘/srv/errbackends’: Permission denied

Docker version 1.10.3, build 20f81dd running on osx 10.11.5

**Comment by rroemhild** [comment]
Errbot starts as user err with the uid 999 and can not write to the directory owned by your host user with a different uid.

```
docker exec err id
uid=999(err) gid=999(err) groups=999(err)
```

**Comment by rchannel** [comment]
Perfect thanks.
