### ISSUE TITLE
Link Docker Hub repository to 'debian' repository

### ISSUE THREAD

**Issue by stefan2904** [rroemhild/docker-err#7]
On Docker hub, in "Build settings", section "Repository Links" (or [here](https://hub.docker.com/r/rroemhild/errbot/~/settings/automated-builds/)), you could add a link to 'debian', to automatically trigger a rebuild of your image every time there is an update of the debian image.

Thanks!

**Comment by rroemhild** [comment]
Thanks! :+1:
